name: General bug/issue report
description: An issue happened while the build script was running or when running a TKG nvidia
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: check-duplicates
    attributes:
      label: Same-issue check
      description: Have you checked that a similar issue isn't already open ? If so, please chime-in there instead of opening another issue.
      options:
        - 'Yes'
    validations:
      required: true
  - type: input
    attributes:
      label: Kernel version
      description: What kernel version have you running when the issue happened?
      placeholder: "6.14.5"
    validations:
      required: true
  - type: input
    id: driver
    attributes:
      label: "NVIDIA driver version / branch"
      description: "What NVIDIA driver version or branch are you trying? e.g. 535.161.07, 470-series, vulkan-dev"
    validations:
      required: true
  - type: dropdown
    id: driver_type
    attributes:
      label: "Driver type"
      description: "Proprietary or open-gpu-kernel-modules driver in use"
      options:
        - "proprietary (nvidia)"
        - "open-gpu-kernel-modules (NVIDIA)"
    validations:
      required: true
  - type: dropdown
    id: dkms
    attributes:
      label: "DKMS used?"
      description: "Was the module installed via DKMS or regular package?"
      options:
        - "YES, DKMS"
        - "NO, Regular"
        - "Both"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        If you know what happened, write it here.

        - Build issues
          - Ideas on what's wrong are welcome (e.g. Patch XYZ is failing on the hunk PYZ, building fails after commit 0705322...).
        - Boot issues
          - Please attach pictures of any message that shows on-screen during the failed boot
        - Runtime issues
          - Please look through `sudo dmesg` to see if any issue is logged

        Notes:
        - If copy-pasting code or from the console, please put ``` in a standalone line before and after
        - Feel free free to drag & drop any relevant text file (needs `.txt` extension)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: |
        Please drag & drop all the files inside the `logs` folder, right after the build issue happened (or for the kernel you've built that have issues).
        Add anything else you deem useful in understanding what's wrong.

        Notes:
        - Arch users: the full build output isn't captured automatically, please re-run `makepkg [args] | tee shell-output.log.txt` then drag & drop that file
    validations:
      required: true
  - type: dropdown
    id: frog
    attributes:
      label: My Favorite type(s) of frog
      multiple: true
      description: What is your favorite frog type ? If we disagree on this, your issue may get ignored entirely, chose wisely...
      options:
        - Frog
        - African Bullfrog (Pyxicephalus adspersus)
        - African Dwarf Frog (Hymenochirus)
        - American Bullfrog (Lithobates catesbeianus)
        - American Cinchona Plantation Treefrog (Isthmohyla rivularis)
        - American Green Tree Frog (Dryophytes cinereus / Hyla cinerea)
        - American Toad (Anaxyrus americanus)
        - Blessed Poison Frog (Ranitomeya benedicta)
        - Bumblebee Dart Frog (Dendrobates leucomelas)
        - Common Frog (Rana temporaria)
        - Cranwell's Horned Frog (Ceratophrys cranwelli)
        - Desert Rain Frog (Breviceps macrops)
        - Glass Frog (Centrolenidae)
        - Golden Mantella (Mantella aurantiaca)
        - Goliath Frog (Conraua goliath)
        - Gray Tree Frogs (Hyla versicolor)
        - Gray Tree frog (Dryophytes versicolor)
        - Green Frog (Lithobates clamitans)
        - Madagascar Tomato Frog (Dyscophus antongilii)
        - Malayan Horned Frog (Megophrys nasuta)
        - Malayan Horned Frog (Pelobatrachus nasutus)
        - Mimic Poison Frog (Ranitomeya imitator)
        - Pacman Frog (Ceratophrys)
        - Painted Reed Frog (Hyperolius marmoratus)
        - Poison Dart Frogs (Dendrobatidae)
        - Red-Backed Poison Frog (Ranitomeya reticulata)
        - Red-Eyed Tree Frog (Agalychnis callidryas)
        - Shovel-Headed Tree Frog (Triprion spatulatus)
        - Spotted tree Frog (Nyctixalus pictus)
        - Strawberry Poison Dart Frog (Oophaga pumilio)
        - True Frogs (Ranidae)
        - Vietnamese mossy Frog (Theloderma corticale)
        - Waxy Monkey Frog (Phyllomedusa sauvagii)
        - Wood Frog (Lithobates sylvaticus)
      default: 0
    validations:
      required: true

